### ISSUE TITLE
请教一个居中样式问题，求大神帮忙看看？

### ISSUE THREAD

**Issue by ForeverPx** [SugarTurboS/Sugar-Community#1]
<img width="153" alt="image" src="https://user-images.githubusercontent.com/7984208/94645654-f0df4b80-031e-11eb-8510-7cb286498179.png">

如上图所看到的文字+ICON按钮，按钮文字的长度是不固定的，由文字长度决定。

如何用纯css实现整个按钮的水平居中？

**Comment by PDKSophia** [comment]
不知道 `absolute` + `transform` 是否能够解决？简单举个例子 :

```html
<div className="box">
  <p>了解更多 ></>
</div>
```
在未知元素宽高情况下，通过 transform 实现居中
```css
.box {
  position: relative;
  height: 48px; // 假设高固定，宽度未知
}
.box p{
  // 垂直水平居中
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

**Comment by SamXChen** [comment]
可以考虑应用 display：table，兼容性也不错
理论上都可以通过添加一个 wrap 标签处理好，有了 wrap 后，无论是 flex 还是 text-align 都可以实现目标效果
![image](https://user-images.githubusercontent.com/17335236/94942165-7a05a680-0508-11eb-991a-00b60424463e.png)

**Comment by ForeverPx** [comment]
> 不知道 `absolute` + `transform` 是否能够解决？简单举个例子 :
> 
> ```
> <div className="box">
>   <p>了解更多 ></>
> </div>
> ```
> 
> 在未知元素宽高情况下，通过 transform 实现居中
> 
> ```css
> .box {
>   position: relative;
>   height: 48px; // 假设高固定，宽度未知
> }
> .box p{
>   // 垂直水平居中
>   position: absolute;
>   top: 50%;
>   left: 50%;
>   transform: translate(-50%, -50%);
> }
> ```

可以的，兼容IE8怎搞

**Comment by ForeverPx** [comment]
这也是其中一种方法 @SamXChen @PDKSophia 

```html
<div class='container'>
  <span class='text'>wdqddqdqdqwqd</span>
</div>
```

```css
.container{
  background-color: red;
  padding: 10px;
  text-align: center;
}

.text{
  background-color: blue;
  display:inline-block;
  padding-right: 20px;
}
```
